# Generated by Django 3.2.4 on 2021-06-19 00:21

from django.db import migrations, models
import django.utils.timezone
import profiles.utils
import sitewide.storage.backend


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, help_text='USER.EMAIL.DESC', max_length=254, unique=True, verbose_name='USER.EMAIL')),
                ('is_superuser', models.BooleanField(default=False, help_text='USER.SUPERUSER.DESC', verbose_name='USER.SUPERUSER')),
                ('is_staff', models.BooleanField(default=False, help_text='USER.STAFF.DESC', verbose_name='USER.STAFF')),
                ('is_active', models.BooleanField(default=True, help_text='USER.ACTIVE.DESC', verbose_name='USER.ACTIVE')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='USER.CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='USER.UPDATED_AT')),
                ('first_name', models.CharField(help_text='USER.FIRST_NAME.DESC', max_length=60, null=True, verbose_name='USER.FIRST_NAME')),
                ('last_name', models.CharField(help_text='USER.LAST_NAME.DESC', max_length=255, null=True, verbose_name='USER.LAST_NAME')),
                ('is_verified', models.BooleanField(default=False, help_text='USER.VERIFIED.DESC', verbose_name='USER.VERIFIED')),
                ('photo', models.ImageField(blank=True, help_text='USER.PHOTO.DESC', max_length=255, null=True, storage=sitewide.storage.backend.MediaFilesStorage(), upload_to=profiles.utils.uploadto_user_photo, verbose_name='USER.PHOTO')),
                ('status', models.CharField(choices=[('new', 'USER.STATUS.NEW'), ('overdue', 'USER.STATUS.OVERDUE'), ('active', 'USER.STATUS.ACTIVE'), ('banned', 'USER.STATUS.BANNED'), ('suspended', 'USER.STATUS.SUSPENDED')], default='new', help_text='USER.STATUS.DESC', max_length=60, verbose_name='USER.STATUS')),
                ('language', models.CharField(default='en', help_text='USER.LANGUAGE.DESC', max_length=40, verbose_name='USER.LANGUAGE')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'USER.LABEL',
                'verbose_name_plural': 'USER.LABEL.PLURAL',
                'permissions': (('read_profile', 'Can read all data on any profile'), ('update_profile', 'Can update public data on any profile'), ('switch_profile', 'Can switch to any non-superuser profile')),
            },
        ),
    ]
